### ISSUE TITLE
Plug was not pulling dynamic data from CUSTOM field. 

### ISSUE THREAD

**Issue by frysteen** [MIGHTYminnow/custom-alt-text-for-elementor-images#1]
When using Elementor Pro and the CUSTOM setting for this plugin, the dynamic data was not being used on the image.

EG: Post title, shortcakes, etc.... (see attached screenshot)

Attached is a fixed version of your files that makes this work.
I tested it on my site, and it works fine - but make sure you do your own testing, of course.

It is attached as a TXT file as I can't attach PHP files... just change the file extension at your end.

![Screenshot 2024-01-12 at 9 58 50 am](https://github.com/MIGHTYminnow/custom-alt-text-for-elementor-images/assets/7022544/44ccd784-fdb3-4b35-84d1-8f38b7bd2c99)

[custom-alt-text-for-elementor-images.txt](https://github.com/MIGHTYminnow/custom-alt-text-for-elementor-images/files/13909690/custom-alt-text-for-elementor-images.txt)

**Comment by aebs90** [comment]
Hello @frysteen 

Thanks for your feedback. It is a great suggestion and we have already published it here and on the [WordPress Plugins Directory](https://wordpress.org/plugins/custom-alt-text-for-elementor-images/).
